[[user_guide]]
= User Guide

This plugin works with non-modular applications, that is, applications that run on the class-path and
don't make use of module descriptors.
Nevertheless, in order to use this plugin, your non-modular application must be compatible with the Java version
of your target JRE (11 or newer).


== Tasks
runtime:: Creates an image containing your application, a custom JRE, and appropriate start scripts.  +
    If the property `distDir` is not set, this task depends on either `installDist` or
    `installShadowDist` (if the https://github.com/johnrengelman/shadow[Shadow plugin] is applied).


runtimeZip:: Creates a zip archive of the custom runtime image. +
    _depends on_: `runtime`

suggestModules:: Displays a list of modules that are probably required by your application.
This list will be used when creating the custom JRE if you don't configure the `modules` property
explicitly within the `runtime` extension. +
Setting the `modules` property explicitly is strongly recommended.
The list of modules suggested by this task is a good value to start with, but it may miss some
required modules or include unnecessary ones, so you may need to adjust it. +
    _depends on_: `jar`

jpackageImage:: Uses the https://jdk.java.net/jpackage/[jpackage] tool to create a platform-specific application image.  +
    _depends on_: `runtime` +

jpackage:: Uses the https://jdk.java.net/jpackage/[jpackage] tool to create a platform-specific application installer.  +
    _depends on_: `jpackageImage` +


== Properties

distDir:: The directory containing the application pre-Java-9-style distribution. +
You rarely need to set this property explicitly, because the plugin automatically
initializes it with the directory in which the `installDist` or the `installShadowDist` task
(if the https://github.com/johnrengelman/shadow[Shadow plugin] is applied) creates the distribution. +
    _usage example_: `distDir = file("$buildDir/install/myapp")`

imageDir:: The directory into which the custom runtime image should be generated. +
(If you use the `targetPlatform` method to generate images for other platforms, the corresponding images will be created in subdirectories of `imageDir`.) +
    _defaultValue_: `_buildDir_/image` +
    _usage example_: `imageDir = file("$buildDir/myapp-image")`

imageZip:: The file into which a zip archive of the custom runtime image should be created. +
    _defaultValue_: `_buildDir_/image.zip"` +
    _usage example_: `imageZip = file("$buildDir/myapp-image.zip")`

options:: A list of options to be passed to _jlink_ when creating the custom JRE. +
    _defaultValue_: empty list +
    _usage example_: `options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']`

javaHome:: The path to the JDK providing the tools needed by the plugin (_javac_, _jar_, _jlink_ etc.). +
    _defaultValue_: the first non-empty value from: +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `badass.runtime.java.home` system property +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `BADASS_RUNTIME_JAVA_HOME` environment variable +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `java.home` system property (only if it points to a JRE containing the `javac`, `jar`, and `jlink` tools) +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `JAVA_HOME` environment variable +
    _usage example_: `javaHome = '/usr/lib/jvm/open-jdk'`

modules:: The list of modules to be included in the custom JRE. +
    _defaultValue_: empty list (the modules provided by the `suggestModules` task will be used) +
    _usage example_: `modules = ['java.naming', 'java.xml']`

additive:: In many cases, the list of modules provided by the `suggestModules` task contains exactly the modules required by your application.
This means that you don’t need to configure the `modules` property, because the plugin can figure out by itself which modules are required.
In some other cases, the "suggested" list of modules is _almost_ right, in the sense that it only misses one or a few modules.
In these cases, you are allowed to specify only the missing modules in the `modules` property,
and you instruct the plugin to add them to the list of suggested modules, by setting the property `additive` to true. +
    _defaultValue_: false +
    _usage example_: `additive = true`

== Methods

[maroon]##addOptions##(String... [purple]##options##):: Adds options to be passed to _jlink_.
It is an alternative way of setting the `options` property.
You can call this method multiple times. +
    _usage example_: `addOptions '--no-header-files', '--no-man-pages'`

[maroon]##targetPlatform##(String [purple]##name##, String [purple]##jdkHome##, List<String> [purple]##options## = []):: Instructs the plugin to generate an application image for a specific platform. +
By default, the plugin generates an image for the platform it runs on.
To create images for other platforms, you need to call the `targetPlatform` method (one call per target platform). +
[purple]##**name**##: an identifier of your choice that will be appended to the `imageDir` and `imageZip` properties to
determine the location of the image directory and of the image archive. +
[purple]##**jdkHome**##: the path to the target platform JDK. +
[purple]##**options**##: an optional list of platform-specific options.
These options will pe passed to _jlink_ in addition to those provided by the `options` property of the `runtime` extension. +
[purple]##_NOTE_##: This is only a convenience method. There is a more powerful `targetPlatform` method (described below), which allows configuring additional parameters of the target platform.

[cols="1,100", frame=none, grid=none]
|===
a| a| .Usage example
[source,groovy]
----
runtime {
    ...
    targetPlatform('linux-x64', '/usr/lib/jvm/jdk_x64_linux_hotspot_11_28')
    targetPlatform('linux-s390x', '/usr/lib/jvm/jdk_s390x_linux_hotspot_11_28',
                                                               ['--endian', 'big'])
    ...
}
----

For a project named `hello`, executing the `runtimeZip` task with the above configuration, and assuming default values for the other properties,
the plugin will generate the platform-specific images in the directories
`build/image/hello-linux-x64` and `build/image/hello-linux-s390x`.
The archived images will be available in `build/image-linux-x64.zip` and `build/image-linux-s390x.zip`.
|===

[maroon]##targetPlatform##(String [purple]##name##, Action<TargetPlatform> [purple]##action##):: This more powerful version of the `targetPlatform` method allows configuring the target platform parameters using a script block. +
[purple]##**name**##: an identifier of your choice that will be appended to the `imageDir` and `imageZip` properties to
determine the location of the image directory and of the image archive. +
[purple]##**action**##: a script block for configuring the target platform parameters. +
&nbsp;&nbsp;&nbsp;&nbsp; _Parameters:_ +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [purple]##**jdkHome**##: the path to the target platform JDK. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [purple]##**options**##: an optional list of platform-specific options. +
&nbsp;&nbsp;&nbsp;&nbsp; _Methods:_ +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [maroon]##addOptions##(String... [purple]##options##): an alternative way of setting the `options` property. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [maroon]##jdkDownload##(String [purple]##downloadUrl##, Closure [purple]##downloadConfig##=null): helper method for setting [purple]##jdkHome##. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It downloads and unpacks a JDK distribution from the given URL. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The optional closure allows configuring the following parameters: +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - [purple]##downloadDir##: the directory in which the distribution is downloaded and unpacked. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _defaultValue_: `_buildDir_/jdks/_targetPlatform-name_` +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - [purple]##archiveName##: the name under which the archived distribution should be saved. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _defaultValue_: `jdk` +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - [purple]##archiveExtension##: accepted values: `tar.gz` and `zip`. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _defaultValue_: `null` (inferred from the URL) +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - [purple]##pathToHome##: the relative path to the JDK home in the unpacked distribution. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _defaultValue_: `null` (inferred by scanning the unpacked distribution) +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - [purple]##overwrite##: if `true`, the plugin overwrites an already existing distribution. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _defaultValue_: `false`

[cols="1,100", frame=none, grid=none]
|===
a| a| .Usage example
[source,groovy]
----
runtime {
    ...
    targetPlatform("linux-s390x") {
        jdkHome = "/usr/lib/jvm/linux-s390x/jdk-14.0.1_7"
        addOptions("--endian", "big")
    }

    targetPlatform("win") {
        jdkHome = jdkDownload("https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.1%2B7.1/OpenJDK14U-jdk_x64_windows_hotspot_14.0.1_7.zip")
    }

    targetPlatform("mac") {
        jdkHome = jdkDownload("https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.1%2B7/OpenJDK14U-jdk_x64_mac_hotspot_14.0.1_7.tar.gz") {
            downloadDir = "$buildDir/myMac"
            archiveName = "my-mac-jdk"
            archiveExtension = "tar.gz"
            pathToHome = "jdk-14.0.1+7/Contents/Home"
            overwrite = true
        }
    }
    ...
}
----
|===

[maroon]##enableCds##(Action<CdsData> [purple]##action## = null):: [red]##Experimental - requires Java 13 or newer## +
Enables Class Data Sharing (CDS). +
[purple]##**action**##: an optional script block for configuring the class data sharing. +
&nbsp;&nbsp;&nbsp;&nbsp; _Parameters:_ +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [purple]##**sharedArchiveFile**##: the path and name of the class data sharing archive file. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It supports the Mustache syntax and placeholders described in the <<launcher>> section. +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _defaultValue:_ +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `lib/server/<appName>.jsa` on Unix-like systems +
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `bin\server\<appName>.jsa` on Windows



[cols="1,100", frame=none, grid=none]
|===
a| a| .Usage example
[source,groovy]
----
runtime {
    ...
    enableCds()
}
----

&nbsp;&nbsp;&nbsp;&nbsp; or

[source,groovy]
----
runtime {
    ...
    enableCds {
        sharedArchiveFile = "{{HOME_DIR}}/${applicationName}.jsa"
    }
}
----

When the `enableCds` method is used, the plugin creates a base CDS archive of the image by executing
`$imageDir/bin/java -Xshare:dump`. This means that you cannot use `enableCds` when targeting another platform.

The plugin also configures a dynamic AppCDS archive in the start scripts.
If no file is found at the `sharedArchiveFile` location, the application is started with the `-XX:ArchiveClassesAtExit` option,
which will create a dynamic AppCDS archive at this location.
Otherwise, the application is started with the `-XX:SharedArchiveFile` option and uses the existing AppCDS archive.

[purple]##_NOTE_##: Start scripts are not included in the installable packages generated by `jpackage`.
As a result, only the base CDS archive of the image is used by the packaged application.


|===

[[scriptBlocks]]
== Script blocks

The `runtime` extension can also contain the script blocks detailed below.

[#launcher]
=== launcher

The plugin generates script files for launching your application.
These script files can be customized by configuring the `launcher` block.

Environment variables can be included by using the https://en.wikipedia.org/wiki/Mustache_(template_system)[Mustache syntax],
that is, by enclosing their name between `{{` and `}}`.
Additionally, you can use the following placeholders:

- `{{BIN_DIR}}` - the _bin_ directory of the custom runtime image
- `{{HOME_DIR}}` - user's home directory (`$HOME` on Unix-like systems, `%USERPROFILE%` on Windows)


jvmArgs:: list of JVM arguments to be passed to the java executable. +
_defaultValue_: the arguments configured in the `applicationDefaultJvmArgs` property of the `application` extension

noConsole:: This boolean property has an effect only on Windows. It is ignored on other platforms. +
If true, the application will be launched without an associated console window (using `javaw` instead of `java`). +
_defaultValue_: false

runInBinDir:: If true, the start script will `cd` in the `bin` directory of the image before executing the application. +
_defaultValue_: false

unixScriptTemplate:: the template for generating the script file for Unix-like systems. +
_defaultValue_: null (the plugin uses its own template)

windowsScriptTemplate:: the template for generating the script file for Windows-based systems. +
_defaultValue_: null (the plugin uses its own template)

The plugin uses http://docs.groovy-lang.org/latest/html/api/groovy/text/SimpleTemplateEngine.html[Groovy's SimpleTemplateEngine]
to parse the templates, with the following variables available:

- applicationName
- mainClassName

_Usage example_
[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
runtime {
    ...
    launcher {
        jvmArgs = [
            '-Dlog4j.debug=true', '-Dlog4j.configurationFile={{BIN_DIR}}/log4j2.xml',
            '-DdbHost', '{{PGHOST}}'
        ]
        unixScriptTemplate = file('unixStartScript.txt')
        windowsScriptTemplate = file('windowsStartScript.txt')
    }
    ...
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
runtime {
    ...
    launcher {
        jvmArgs = listOf(
            "-Dlog4j.debug=true", "-Dlog4j.configurationFile={{BIN_DIR}}/log4j2.xml",
            "-DdbHost", "{{PGHOST}}"
        )
        unixScriptTemplate = file("unixStartScript.txt")
        windowsScriptTemplate = file("windowsStartScript.txt")
    }
    ...
}
----


=== jpackage

This script block allows you to customize the https://jdk.java.net/jpackage/[jpackage]-based generation of platform-specific application images and installers.

jpackageHome:: The path to the JDK providing the jpackage tool. +
    _defaultValue_: the first non-empty value from: +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `badass.runtime.jpackage.home` system property +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `BADASS_RUNTIME_JPACKAGE_HOME` environment variable +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `java.home` system property (only if it points to a JRE containing the `jpackage` tool) +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `JAVA_HOME` environment variable +
    _usage example_: `jpackageHome = "/usr/lib/jvm/jdk14"`

outputDir:: Convenience property for setting both `imageOutputDir` and
`installerOutputDir` with the value _buildDir_/_outputDir_. +
    _defaultValue_: `"jpackage"` +
    _usage example_: `outputDir = "my-packaging"`


imageOutputDir:: the directory passed as argument to the `--output` option when running `jpackage` to create an application image. +
    _defaultValue_: `_buildDir_/_outputDir_` +
    _usage example_: `imageOutputDir = file("$buildDir/my-packaging-image")`

imageName:: the argument passed to the `--name` option when running `jpackage` to create an application image. +
    _defaultValue_: `_project.name_` +
    _usage example_: `imageName = "MyApp"`

imageOptions:: list of additional options to be passed to the `jpackage` executable when creating the appliction image. +
    _defaultValue_: empty list +
    _usage example_: `imageOptions = ["--win-console"]`

resourceDir:: the directory passed as argument to the `--resource-dir` option when running `jpackage` to create an application installer.
It is also applicable when creating an application image when you want your own application image instead of the default java image. +
    _usage example_: `resourceDir = file("$buildDir/my-packaging-resources")`

skipInstaller:: boolean value that lets you generate only the platform-specific application image and skip the generation of the platform-specific application installer. +
    _defaultValue_: false +
    _usage example_: `skipInstaller = true`

installerType:: the type of installer to be generated. +
    _defaultValue_: null (all supported types for the current platform will be generated) +
    _usage example_: `installerType = "rpm"`

installerOutputDir:: the directory passed as argument to the `--output` option when running `jpackage` to create an application installer. +
    _defaultValue_: `_buildDir_/_outputDir_` +
    _usage example_: `installerOutputDir = file("$buildDir/my-packaging-installer")`

installerName:: the argument passed to the `--name` option when running `jpackage` to create an application installer. +
    _defaultValue_: `_project.name_` +
    _usage example_: `installerName = "MyApp"`

jvmArgs:: list of JVM arguments to be passed to the virtual machine. +
    _defaultValue_: the `jvmArgs` value configured in the `launcher` block, or the arguments configured in the `applicationDefaultJvmArgs` property of the `application` extension. +
[purple]##_NOTE_##: If the default value is used, and it contains the placeholder `{{BIN_DIR}}`, the plugin replaces this placeholder with `$APPDIR/..` when passing the arguments to `jpackage`.
This is the correct approach in most cases. If it doesn't work in your case, you need to explicitly configure *jvmArgs* in the `jpackage` block. +
Currently, jpackage doesn't support environment variables in `--java-options`. Therefore, you cannot use environment variable names enclosed between `{{` and `}}` in `jvmArgs`.

args:: list of arguments to be passed to the application. +
    _defaultValue_: the arguments configured in the `args` property of the `run` task

appVersion:: the argument passed to the `--app-version` option when running `jpackage` when executing the `jpackage` and `jpackageImage` tasks. +
    _defaultValue_: the project version +
    _usage example_: `appVersion = "1.0.0"`

installerOptions:: list of additional options to be passed to the `jpackage` executable when creating the application installer. +
    _defaultValue_: empty list +
    _usage example_: `installerOptions = ["--win-console"]`

targetPlatformName:: This property is required only when using the `targetPlatform` method.
    It specifies which of the images produced by jlink should be used as runtime image by jpackage.
    Its value must match the name provided in one of the calls to the `targetPlatform` method. +
    _defaultValue_: null +
    _usage example_: `targetPlatform = "linux"`

mainJar:: the argument passed to the `--main-jar` option when running `jpackage` to create an application image. +
    Usually, you don't need to set this property, unless you also explicitly set `distDir`. +
    _defaultValue_: the name of the JAR file produced by the `installDist` or the `installShadowDist` task +
    _usage example_: `mainJar = "my-app-1.0.1.jar"`

mainClass:: the argument passed to the `--main-class` option when running `jpackage` to create an application image. +
    Usually, you don't need to set this property, unless you also explicitly set `distDir`. +
    _defaultValue_: the `mainClassName` configured for the `application` plugin +
    _usage example_: `mainClass = "org.example.hello.Greeter"`


_Usage example_
[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
runtime {
    ...
    jpackage {
        jpackageHome = '/usr/lib/jvm/jdk14'
        outputDir = 'my-packaging'
        // imageOutputDir = file("$buildDir/my-packaging-image")
        // installerOutputDir = file("$buildDir/my-packaging-installer")
        imageName = 'MyApp'
        imageOptions = ['--win-console']
        skipInstaller = false
        installerName = 'MyApp'
        installerType = 'msi'
        installerOptions = ['--win-menu', '--win-shortcut']
    }
    ...
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
runtime {
    ...
    jpackage {
        jpackageHome = "/usr/lib/jvm/jdk14"
        outputDir = "my-packaging"
        // imageOutputDir = file("$buildDir/my-packaging-image")
        // installerOutputDir = file("$buildDir/my-packaging-installer")
        imageName = "MyApp"
        imageOptions = listOf("--win-console")
        skipInstaller = false
        installerName = "MyApp"
        installerType = "msi"
        installerOptions = listOf("--win-menu", "--win-shortcut")
    }
    ...
}
----



