[[user_guide]]
= User Guide

This plugin works with non-modular applications, that is, applications that run on the class-path and
don't make use of module descriptors.
Nevertheless, in order to use this plugin, your non-modular application must be compatible with the Java version
of your target JRE (11 or newer).


== Tasks
runtime:: Creates an image containing your application, a custom JRE, and appropriate start scripts.  +
    If the property `distDir` is not set, this task depends on either `installDist` or
    `installShadowDist` (if the https://github.com/johnrengelman/shadow[Shadow plugin] is applied).


runtimeZip:: Creates a zip archive of the custom runtime image. +
    _depends on_: `runtime`


suggestModules:: Displays a list of modules that are probably required by your application.
This list will be used when creating the custom JRE if you don't configure the `modules` property
explicitly within the `runtime` extension. +
Setting the `modules` property explicitly is strongly recommended.
The list of modules suggested by this task is a good value to start with, but it may miss some
required modules or include unnecessary ones, so you may need to adjust it. +
    _depends on_: `jar`


== Properties

distDir:: The directory containing the application pre-Java-9-style distribution. +
You rarely need to set this property explicitly, because the plugin automatically
initializes it with the directory in which the `installDist` or the `installShadowDist` task
(if the https://github.com/johnrengelman/shadow[Shadow plugin] is applied) creates the distribution.

imageDir:: The directory into which the custom runtime image should be generated. +
(If you use the `targetPlatform` method to generate images for other platforms, the corresponding images will be created in subdirectories of `imageDir`.) +
    _defaultValue_: `_buildDir_/image` +
    _usage example_: `imageDir = file("$buildDir/myapp-image")`

imageZip:: The file into which a zip archive of the custom runtime image should be created. +
    _defaultValue_: `_buildDir_/image.zip"` +
    _usage example_: `imageZip = file("$buildDir/myapp-image.zip")`

options:: A list of options to be passed to _jlink_ when creating the custom JRE. +
    _defaultValue_: empty list +
    _usage example_: `options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']`

javaHome:: The path to the JDK providing the _jlink_ tool. +
Unless you call the _targetPlatform_ method, the modules included in the custom JRE will also come from this JDK. +
    _defaultValue_: the value of the `JAVA_HOME` environment variable. +
    _usage example_: `javaHome = '/usr/lib/jvm/open-jdk'`

modules:: The list of modules to be included in the custom JRE. +
    _defaultValue_: empty list (the modules provided by the `suggestModules` task will be used) +
    _usage example_: `modules = ['java.naming', 'java.xml']`



== Methods

[maroon]##addOptions##(String... [purple]##options##):: Adds options to be passed to _jlink_.
It is an alternative way of setting the `options` property.
You can call this method multiple times. +
    _usage example_: `addOptions '--no-header-files', '--no-man-pages'`

[maroon]##targetPlatform##(String [purple]##name##, String [purple]##jdkHome##, List<String> [purple]##options## = []):: Instructs the plugin to generate an application image for a specific platform. +
By default, the plugin generates an image for the platform it runs on.
To create images for other platforms, you need to call the `targetPlatform` method (one call per target platform). +
[purple]##**name**##: an identifier of your choice that will be appended to the `imageDir` and `imageZip` properties to
determine the location of the image directory and of the image archive. +
[purple]##**jdkHome**##: the path to the target platform JDK. +
[purple]##**options**##: an optional list of platform-specific options.
These options will pe passed to _jlink_ in addition to those provided by the `options` property of the `runtime` extension.

[cols="1,100", frame=none, grid=none]
|===
a| a| .Usage example
[source,groovy]
----
runtime {
    ...
    targetPlatform('linux-x64', '/usr/lib/jvm/jdk_x64_linux_hotspot_11_28')
    targetPlatform('linux-s390x', '/usr/lib/jvm/jdk_s390x_linux_hotspot_11_28',
                                                               ['--endian', 'big'])
    ...
}
----

For a project named `hello`, executing the `runtimeZip` task with the above configuration, and assuming default values for the other properties,
the plugin will generate the platform-specific images in the directories
`build/image/hello-linux-x64` and `build/image/hello-linux-s390x`.
The archived images will be available in `build/image-linux-x64.zip` and `build/image-linux-s390x.zip`.
|===
