[[user_guide]]
= User Guide

This plugin works with non-modular applications, that is, applications that run on the class-path and
don't make use of module descriptors.
Nevertheless, in order to use this plugin, your non-modular application must be compatible with the Java version
of your target JRE (11 or newer).


== Tasks
runtime:: Creates an image containing your application, a custom JRE, and appropriate start scripts.  +
    If the property `distDir` is not set, this task depends on either `installDist` or
    `installShadowDist` (if the https://github.com/johnrengelman/shadow[Shadow plugin] is applied).


runtimeZip:: Creates a zip archive of the custom runtime image. +
    _depends on_: `runtime`

suggestModules:: Displays a list of modules that are probably required by your application.
This list will be used when creating the custom JRE if you don't configure the `modules` property
explicitly within the `runtime` extension. +
Setting the `modules` property explicitly is strongly recommended.
The list of modules suggested by this task is a good value to start with, but it may miss some
required modules or include unnecessary ones, so you may need to adjust it. +
    _depends on_: `jar`

jpackageImage:: Uses the https://jdk.java.net/jpackage/[jpackage] tool to create a platform-specific application image.  +
    _depends on_: `runtime` +
    _This task is experimental._

jpackage:: Uses the https://jdk.java.net/jpackage/[jpackage] tool to create a platform-specific application installer.  +
    _depends on_: `jpackageImage` +
    _This task is experimental._


== Properties

distDir:: The directory containing the application pre-Java-9-style distribution. +
You rarely need to set this property explicitly, because the plugin automatically
initializes it with the directory in which the `installDist` or the `installShadowDist` task
(if the https://github.com/johnrengelman/shadow[Shadow plugin] is applied) creates the distribution. +
    _usage example_: `distDir = file("$buildDir/install/myapp")`

imageDir:: The directory into which the custom runtime image should be generated. +
(If you use the `targetPlatform` method to generate images for other platforms, the corresponding images will be created in subdirectories of `imageDir`.) +
    _defaultValue_: `_buildDir_/image` +
    _usage example_: `imageDir = file("$buildDir/myapp-image")`

imageZip:: The file into which a zip archive of the custom runtime image should be created. +
    _defaultValue_: `_buildDir_/image.zip"` +
    _usage example_: `imageZip = file("$buildDir/myapp-image.zip")`

options:: A list of options to be passed to _jlink_ when creating the custom JRE. +
    _defaultValue_: empty list +
    _usage example_: `options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']`

javaHome:: The path to the JDK providing the tools needed by the plugin (_javac_, _jar_, _jlink_ etc.). +
    _defaultValue_: the first non-empty value from: +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `badass.runtime.java.home` system property +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `BADASS_RUNTIME_JAVA_HOME` environment variable +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `java.home` system property (only if it points to a JRE containing the `javac`, `jar`, and `jlink` tools) +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `JAVA_HOME` environment variable +
    _usage example_: `javaHome = '/usr/lib/jvm/open-jdk'`

modules:: The list of modules to be included in the custom JRE. +
    _defaultValue_: empty list (the modules provided by the `suggestModules` task will be used) +
    _usage example_: `modules = ['java.naming', 'java.xml']`



== Methods

[maroon]##addOptions##(String... [purple]##options##):: Adds options to be passed to _jlink_.
It is an alternative way of setting the `options` property.
You can call this method multiple times. +
    _usage example_: `addOptions '--no-header-files', '--no-man-pages'`

[maroon]##targetPlatform##(String [purple]##name##, String [purple]##jdkHome##, List<String> [purple]##options## = []):: Instructs the plugin to generate an application image for a specific platform. +
By default, the plugin generates an image for the platform it runs on.
To create images for other platforms, you need to call the `targetPlatform` method (one call per target platform). +
[purple]##**name**##: an identifier of your choice that will be appended to the `imageDir` and `imageZip` properties to
determine the location of the image directory and of the image archive. +
[purple]##**jdkHome**##: the path to the target platform JDK. +
[purple]##**options**##: an optional list of platform-specific options.
These options will pe passed to _jlink_ in addition to those provided by the `options` property of the `runtime` extension.

[cols="1,100", frame=none, grid=none]
|===
a| a| .Usage example
[source,groovy]
----
runtime {
    ...
    targetPlatform('linux-x64', '/usr/lib/jvm/jdk_x64_linux_hotspot_11_28')
    targetPlatform('linux-s390x', '/usr/lib/jvm/jdk_s390x_linux_hotspot_11_28',
                                                               ['--endian', 'big'])
    ...
}
----

For a project named `hello`, executing the `runtimeZip` task with the above configuration, and assuming default values for the other properties,
the plugin will generate the platform-specific images in the directories
`build/image/hello-linux-x64` and `build/image/hello-linux-s390x`.
The archived images will be available in `build/image-linux-x64.zip` and `build/image-linux-s390x.zip`.
|===

== The jpackage script block

This experimental script block allows you to customize the https://jdk.java.net/jpackage/[jpackage]-based generation of platform-specific application images and installers.

jpackageHome:: The path to the JDK providing the jpackage tool. +
    _defaultValue_: the first non-empty value from: +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `badass.runtime.jpackage.home` system property +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `BADASS_RUNTIME_JPACKAGE_HOME` environment variable +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `java.home` system property (only if it points to a JRE containing the `jpackage` tool) +
        pass:[&nbsp;&nbsp;&nbsp;&nbsp;] - the `JAVA_HOME` environment variable +
    _usage example_: `jpackageHome = "/usr/lib/jvm/jdk14"`

outputDir:: Convenience property for setting both `imageOutputDir` and
`installerOutputDir` with the value _buildDir_/_outputDir_. +
    _defaultValue_: `"jpackage"` +
    _usage example_: `outputDir = "my-packaging"`


imageOutputDir:: the directory passed as argument to the `--output` option when running `jpackage` to create an application image. +
    _defaultValue_: `_buildDir_/_outputDir_` +
    _usage example_: `imageOutputDir = file("$buildDir/my-packaging-image")`

imageName:: the argument passed to the `--name` option when running `jpackage` to create an application image. +
    _defaultValue_: the `name` value configured in the `launcher` block or  `_project.name_` +
    _usage example_: `imageName = "MyApp"`

imageOptions:: list of additional options to be passed to the `jpackage` executable when creating the appliction image. +
    _defaultValue_: empty list +
    _usage example_: `imageOptions = ["--win-console"]`

skipInstaller:: boolean value that lets you generate only the platform-specific application image and skip the generation of the platform-specific application installer. +
    _defaultValue_: false +
    _usage example_: `skipInstaller = true`

installerType:: the type of installer to be generated. +
    _defaultValue_: null (all supported types for the current platform will be generated) +
    _usage example_: `installerType = "rpm"`

installerOutputDir:: the directory passed as argument to the `--output` option when running `jpackage` to create an application installer. +
    _defaultValue_: `_buildDir_/_outputDir_` +
    _usage example_: `installerOutputDir = file("$buildDir/my-packaging-installer")`

installerName:: the argument passed to the `--name` option when running `jpackage` to create an application installer. +
    _defaultValue_: the `name` value configured in the `launcher` block or  `_project.name_` +
    _usage example_: `installerName = "MyApp"`

jvmArgs:: list of JVM arguments to be passed to the virtual machine. +
    _defaultValue_: the `jvmArgs` value configured in the `launcher` block or an empty list

identifier:: the argument passed to the `--identifier` option when running `jpackage` when executing the `jpackage` and `jpackageImage` tasks. +
    _defaultValue_: the main class name +
    _usage example_: `identifier = "org.example.MyApp"`

appVersion:: the argument passed to the `--app-version` option when running `jpackage` when executing the `jpackage` task. +
    _defaultValue_: the project version +
    _usage example_: `appVersion = "1.0.0"`

installerOptions:: list of additional options to be passed to the `jpackage` executable when creating the application installer. +
    _defaultValue_: empty list +
    _usage example_: `installerOptions = ["--win-console"]`

targetPlatformName:: This property is required only when using the `targetPlatform` method.
    It specifies which of the images produced by jlink should be used as runtime image by jpackage.
    Its value must match the name provided in one of the calls to the `targetPlatform` method. +
    _defaultValue_: null +
    _usage example_: `targetPlatform = "linux"`

mainJar:: the argument passed to the `--main-jar` option when running `jpackage` to create an application image. +
    Usually, you don't need to set this property, unless you also explicitly set `distDir`. +
    _defaultValue_: the name of the JAR file produced by the `installDist` or the `installShadowDist` task +
    _usage example_: `mainJar = "my-app-1.0.1.jar"`

mainClass:: the argument passed to the `--main-class` option when running `jpackage` to create an application image. +
    Usually, you don't need to set this property, unless you also explicitly set `distDir`. +
    _defaultValue_: the `mainClassName` configured for the `application` plugin +
    _usage example_: `mainClass = "org.example.hello.Greeter"`


_Usage example_
[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
runtime {
    ...
    jpackage {
        jpackageHome = '/usr/lib/jvm/jdk14'
        outputDir = 'my-packaging'
        // imageOutputDir = file("$buildDir/my-packaging-image")
        // installerOutputDir = file("$buildDir/my-packaging-installer")
        imageName = 'MyApp'
        imageOptions = ['--win-console']
        skipInstaller = false
        installerName = 'MyApp'
        installerType = 'msi'
        installerOptions = ['--win-menu', '--win-shortcut']
    }
    ...
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
runtime {
    ...
    jpackage {
        jpackageHome = "/usr/lib/jvm/jdk14"
        outputDir = "my-packaging"
        // imageOutputDir = file("$buildDir/my-packaging-image")
        // installerOutputDir = file("$buildDir/my-packaging-installer")
        imageName = "MyApp"
        imageOptions = listOf("--win-console")
        skipInstaller = false
        installerName = "MyApp"
        installerType = "msi"
        installerOptions = listOf("--win-menu", "--win-shortcut")
    }
    ...
}
----



