name: Java 11 Gradle CI

on: [push]

jobs:
  build:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17 (default)
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for publish.sh
        run: chmod +x publish.sh
      - name: Build and run asciidoc
        run: ./gradlew -is build groovydoc asciidoc --scan
      - name: Run publish if necessary
        env: # Or as an environment variable
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
        run: ./publish.sh
